# -*- makefile -*-
# $Id: Makefile.rules,v 1.3 2003/09/10 13:56:35 raven Exp $
#
# Makefile rules for autofs project
#

# Root directory contents
SUBDIRS = daemon modules man
INCDIRS = include samples
INCFILES = COPYING COPYRIGHT NEWS README* TODO Makefile Makefile.rules \
	   Makefile.conf.in .version .autofs-* configure.in aclocal.m4 \
	   configure *.patch autofs.spec

# Compilers, linkers and flags
# The STRIP defined here *must not* remove any dynamic-loading symbols

ifdef DEBUG
CFLAGS    = -O2 -g -DDEBUG
LDFLAGS   = -g
STRIP     = :
else
CFLAGS    = -O3 -fomit-frame-pointer -Wall
LDFLAGS   = -s
STRIP     = strip --strip-debug
endif

CC        = gcc
CXX       = g++
CXXFLAGS  = $(CFLAGS)
LD        = ld
SOLDFLAGS = -shared

# Standard rules

.SUFFIXES: .c .o .s .so

.c.o:
	$(CC) $(CFLAGS) -c $<

.c.s:
	$(CC) $(CFLAGS) -S $<

.c.so:
	$(CC) $(SOLDFLAGS) $(CFLAGS) -o $*.so $<
	$(STRIP) $*.so
